export interface SwagProduct {
  id: string;
  name: string;
  price: number;
  category: 'apparel' | 'stickers' | 'drinkware' | 'bags' | 'hats' | 'accessories';
  description: string;
  blurb?: string;
  image: string;
  printfulUrl: string;
  tag?: string;
  variants?: { label: string; value: string }[];
  audience: 'for-you' | 'for-staff' | 'both';
}

function img(id: string): string {
  return `/images/swag/${id}.webp`;
}

export const SWAG_PRODUCTS: SwagProduct[] = [
  {
    id: 'ask-me-tee',
    name: 'Ask Me',
    price: 38.00,
    category: 'apparel',
    description: 'Pigment-dyed heavyweight tee',
    blurb: 'The one that starts conversations in the grocery store.',
    image: img('ask-me-tee'),
    printfulUrl: 'https://tdi.printful.me/product/ask-me-unisex-garment-dyed-creator-20-vintage-t-shirt-stanleystella-satu041',
    variants: [
      { label: 'S', value: 's' },
      { label: 'M', value: 'm' },
      { label: 'L', value: 'l' },
      { label: 'XL', value: 'xl' },
      { label: '2XL', value: '2xl' },
    ],
    audience: 'both',
  },
  {
    id: 'room-hat',
    name: 'The Room',
    price: 32.00,
    category: 'hats',
    description: 'Embroidered dad hat',
    blurb: 'Stitched, not printed.',
    image: img('room-hat'),
    printfulUrl: 'https://tdi.printful.me/product/room-5-panel-cap',
    audience: 'both',
  },
  {
    id: 'good-stuff-tee',
    name: 'The Good Stuff',
    price: 36.00,
    category: 'apparel',
    description: 'Heather Olive tee',
    blurb: 'For the quiet list of things that should have been obvious.',
    image: img('good-stuff-tee'),
    printfulUrl: 'https://tdi.printful.me/product/the-good-stuff-unisex-garment-dyed-creator-20-vintage-t-shirt-stanleystella-satu041',
    variants: [
      { label: 'S', value: 's' },
      { label: 'M', value: 'm' },
      { label: 'L', value: 'l' },
      { label: 'XL', value: 'xl' },
      { label: '2XL', value: '2xl' },
    ],
    audience: 'for-you',
  },
  {
    id: 'good-pens-tumbler',
    name: 'The Good Pens',
    price: 34.00,
    category: 'drinkware',
    description: '20 oz insulated tumbler',
    blurb: 'Holds ice through a double period.',
    image: img('good-pens-tumbler'),
    printfulUrl: 'https://tdi.printful.me/product/the-good-pens-clear-plastic-tumbler',
    audience: 'both',
  },
  {
    id: 'best-part-mug',
    name: "Somebody's Best Part",
    price: 26.00,
    category: 'drinkware',
    description: 'Black glossy mug, 11oz',
    blurb: 'For the teacher you would like to keep.',
    image: img('best-part-mug'),
    printfulUrl: 'https://tdi.printful.me/product/best-part-black-glossy-mug',
    audience: 'for-staff',
  },
  {
    id: 'para-ask-tee',
    name: 'Ask the Para',
    price: 33.50,
    category: 'apparel',
    description: 'Vintage fit tee',
    blurb: 'Because they always know.',
    image: img('para-ask-tee'),
    printfulUrl: 'https://tdi.printful.me/product/para-ask-unisex-garment-dyed-creator-20-vintage-t-shirt-stanleystella-satu041',
    tag: 'Para Line',
    variants: [
      { label: 'S', value: 's' },
      { label: 'M', value: 'm' },
      { label: 'L', value: 'l' },
      { label: 'XL', value: 'xl' },
      { label: '2XL', value: '2xl' },
    ],
    audience: 'both',
  },
  {
    id: 'hard-parts-tote',
    name: 'The Hard Parts',
    price: 36.50,
    category: 'bags',
    description: 'Organic denim tote',
    image: img('hard-parts-tote'),
    printfulUrl: 'https://tdi.printful.me/product/hard-parts-organic-denim-tote-bag',
    audience: 'for-you',
  },
  {
    id: 'same-team-tote',
    name: 'Same Team',
    price: 28.00,
    category: 'bags',
    description: 'Eco recycled cotton',
    image: img('same-team-tote'),
    printfulUrl: 'https://tdi.printful.me/product/same-team-eco-tote-bag',
    audience: 'both',
  },
  {
    id: 'pa-hat',
    name: 'The PA',
    price: 16.00,
    category: 'hats',
    description: '5-panel, adjustable',
    image: img('pa-hat'),
    printfulUrl: 'https://tdi.printful.me/product/pa-hat-5-panel-cap',
    audience: 'for-you',
  },
  {
    id: 'same-team-magnet',
    name: 'Same Team',
    price: 8.00,
    category: 'accessories',
    description: 'Round magnet',
    image: img('same-team-magnet'),
    printfulUrl: 'https://tdi.printful.me/product/same-team-magnet',
    audience: 'for-you',
  },
  // ─── New products ───
  {
    id: 'staff-tee',
    name: 'The Staff',
    price: 33.50,
    category: 'apparel',
    description: 'Vintage fit tee',
    blurb: 'The title that covers everything.',
    image: img('staff-tee'),
    printfulUrl: 'https://tdi.printful.me/product/staff-unisex-garment-dyed-creator-20-vintage-t-shirt-stanleystella-satu041',
    variants: [
      { label: 'S', value: 's' },
      { label: 'M', value: 'm' },
      { label: 'L', value: 'l' },
      { label: 'XL', value: 'xl' },
      { label: '2XL', value: '2xl' },
    ],
    audience: 'for-staff',
  },
  {
    id: 'notebook',
    name: 'The Notebook',
    price: 17.50,
    category: 'accessories',
    description: 'Hardcover bound',
    blurb: 'For the plans that actually matter.',
    image: img('notebook'),
    printfulUrl: 'https://tdi.printful.me/product/hardcover-bound-notebook',
    audience: 'for-you',
  },
  {
    id: 'laptop-sleeve',
    name: 'The Sleeve',
    price: 28.00,
    category: 'accessories',
    description: 'Padded laptop sleeve',
    blurb: 'Protect the thing that holds everything.',
    image: img('laptop-sleeve'),
    printfulUrl: 'https://tdi.printful.me/product/laptop-sleeve',
    audience: 'for-you',
  },
  {
    id: 'eco-tote-new',
    name: 'The Carry',
    price: 30.00,
    category: 'bags',
    description: 'Eco tote bag',
    image: img('eco-tote-new'),
    printfulUrl: 'https://tdi.printful.me/product/eco-tote-bag',
    audience: 'both',
  },
  {
    id: 'tumbler-new',
    name: 'The Tumbler',
    price: 13.50,
    category: 'drinkware',
    description: 'Clear plastic, 16oz',
    blurb: 'See what you are drinking. Stay hydrated.',
    image: img('tumbler-new'),
    printfulUrl: 'https://tdi.printful.me/product/clear-plastic-tumbler',
    audience: 'both',
  },
  {
    id: 'same-team-sticker-sm',
    name: 'Same Team',
    price: 3.00,
    category: 'stickers',
    description: 'Bubble-free vinyl',
    image: img('same-team-sticker-sm'),
    printfulUrl: 'https://tdi.printful.me/product/same-team-bubble-free-stickers-6a67cb7a75b74',
    audience: 'for-you',
  },
  {
    id: 'job-varies-sticker',
    name: 'Job Varies',
    price: 3.00,
    category: 'stickers',
    description: 'Bubble-free vinyl',
    image: img('job-varies-sticker'),
    printfulUrl: 'https://tdi.printful.me/product/job-varies-bubble-free-stickers',
    audience: 'for-you',
  },
  {
    id: 'someone-sticker',
    name: 'Someone',
    price: 3.00,
    category: 'stickers',
    description: 'Bubble-free vinyl',
    image: img('someone-sticker'),
    printfulUrl: 'https://tdi.printful.me/product/someone-bubble-free-stickers',
    audience: 'for-you',
  },
  {
    id: 'tdi-sticker',
    name: 'TDI',
    price: 3.00,
    category: 'stickers',
    description: 'Bubble-free vinyl',
    image: img('tdi-sticker'),
    printfulUrl: 'https://tdi.printful.me/product/tdi-bubble-free-stickers',
    audience: 'for-you',
  },
  {
    id: 'glad-sticker',
    name: 'Glad',
    price: 3.00,
    category: 'stickers',
    description: 'Bubble-free vinyl',
    image: img('glad-sticker'),
    printfulUrl: 'https://tdi.printful.me/product/glad-bubble-free-stickers',
    audience: 'for-you',
  },
  {
    id: 'same-team-sticker-lg',
    name: 'Same Team (Large)',
    price: 7.00,
    category: 'stickers',
    description: 'Bubble-free vinyl, large',
    image: img('same-team-sticker-lg'),
    printfulUrl: 'https://tdi.printful.me/product/same-team-bubble-free-stickers',
    audience: 'for-you',
  },
];

export function getProductsByAudience(audience: 'for-you' | 'for-staff'): SwagProduct[] {
  return SWAG_PRODUCTS.filter(p => p.category !== 'stickers' && (p.audience === audience || p.audience === 'both'));
}

export function getStickers(): SwagProduct[] {
  return SWAG_PRODUCTS.filter(p => p.category === 'stickers');
}
