'use client';

import Link from 'next/link';
import { ArrowLeft, Printer } from 'lucide-react';

const SECTIONS = [
  {
    number: 1,
    title: 'SCOPE OF WORK',
    content: `Creator agrees to develop original educational content ("Content") for distribution on TDI's platform. Content may include courses, downloads, blog posts, and marketing materials as mutually agreed.

TDI will provide production support, platform hosting, marketing distribution, and administrative infrastructure.

Creator retains full creative control over their Content, subject to TDI's brand and quality guidelines.`,
  },
  {
    number: 2,
    title: 'AFFILIATE REVENUE SHARE',
    content: `2.1 Sole Compensation. Creator's sole compensation under this Agreement is a 50% share of Affiliate Revenue.

2.2 Definition. "Affiliate Revenue" means the net revenue (gross revenue minus payment processing fees, taxes/regulatory charges, and refunds) generated by users who sign up to TDI through Creator's unique affiliate link. Revenue accrues regardless of which Creator's content the referred user ultimately purchases.

2.3 Payment Schedule. Payouts are made monthly by the 15th of the following month, accompanied by a transparency statement itemizing each conversion, gross amount, deductions, and net payout.

2.4 Affiliate Link Duration. Affiliate tracking cookies persist for 90 days from the date of click. Creator's affiliate link remains active for the duration of this Agreement and during any paused period.

2.5 No Deductions. TDI will never deduct overhead, platform costs, or operating expenses from Creator's share.`,
  },
  {
    number: 3,
    title: 'INTELLECTUAL PROPERTY OWNERSHIP AND LICENSING',
    content: `3.1 Assignment. Creator assigns to TDI ownership of the final published version of Content created under this Agreement ("Work Product"). This assignment enables TDI to distribute, market, sublicense, and protect the Content.

3.2 Creator IP. Creator retains ownership of all pre-existing materials, frameworks, templates, and methodologies brought to the project ("Creator IP").

3.3 Portfolio Rights. Creator may reference the Work Product in professional portfolios, list TDI as a client, and describe the work publicly. TDI grants Creator a perpetual, non-exclusive license to reference the Work Product for personal branding purposes.`,
  },
  {
    number: 4,
    title: 'BRAND COMPLIANCE',
    content: `Creator agrees to follow TDI's brand guidelines when creating Content for the platform. TDI will provide current brand guidelines and notify Creator of material updates.

Creator's independent work, social media presence, and personal brand remain entirely under Creator's control.`,
  },
  {
    number: 5,
    title: 'FERPA AND STUDENT DATA OBLIGATIONS',
    content: `Creator shall not include personally identifiable student information (names, images, performance data, behavioral records) in Content unless proper written consent has been obtained per applicable law.

If Content involves filming in educational settings, Creator will coordinate with the institution's administration to ensure compliance with their media/consent policies.

TDI will provide guidance and support for FERPA compliance as needed.`,
  },
  {
    number: 6,
    title: 'CONFIDENTIALITY',
    content: `Each party agrees to protect the other's confidential business information (financials, strategies, unpublished content, proprietary methods) and not disclose it to third parties without written consent.

Confidential information does not include information that is publicly available, independently developed, or required to be disclosed by law.`,
  },
  {
    number: 7,
    title: 'TERM AND TERMINATION',
    content: `This Agreement is effective upon signing and continues until terminated. Either party may terminate with 14 days' written notice.

Upon termination:
(a) All earned but unpaid compensation will be paid within 30 days.
(b) TDI retains license to continue distributing existing Content.
(c) Creator's affiliate link is deactivated and no new revenue accrues after the termination date.`,
  },
  {
    number: 8,
    title: 'EXCLUSIVITY AND NON-COMPETE',
    content: `8.1 Default: Non-Exclusive (Option A). Creator is free to create content for other platforms, run independent businesses, and engage in any professional activities.

Creator agrees not to recreate substantially the same Content for a direct competitor of TDI during the term of this Agreement. "Direct competitor" means a platform that offers paid professional development courses specifically for K-12 educators.`,
  },
  {
    number: 9,
    title: 'REPRESENTATIONS AND WARRANTIES',
    content: `Creator represents that:
(a) They have the legal capacity to enter this Agreement.
(b) The Content they create is original or properly licensed.
(c) The Content does not infringe any third party's intellectual property rights.
(d) They will comply with applicable laws including FERPA.

TDI represents that:
(a) It has the authority to enter this Agreement.
(b) It will maintain the platform in good working order.
(c) It will make timely payments as described in Section 2.`,
  },
  {
    number: 10,
    title: 'INDEMNIFICATION',
    content: `Each party agrees to indemnify and hold harmless the other party from claims, damages, and expenses (including reasonable attorney's fees) arising from:
(a) Breach of this Agreement.
(b) Violation of applicable law.
(c) Infringement of third-party rights.

The indemnifying party will have reasonable opportunity to participate in the defense of any claim.`,
  },
  {
    number: 11,
    title: 'LIMITATION OF LIABILITY',
    content: `Neither party's total liability under this Agreement shall exceed the greater of (a) the total compensation paid or payable in the 12 months preceding the claim, or (b) $1,000.

Neither party shall be liable for indirect, incidental, consequential, or punitive damages.

This limitation does not apply to breaches of confidentiality, willful misconduct, or indemnification obligations.`,
  },
  {
    number: 12,
    title: 'GENERAL PROVISIONS',
    content: `12.1 Governing Law. This Agreement is governed by the laws of the State of Illinois.

12.2 Dispute Resolution. Good faith negotiation for 30 days, then binding arbitration under AAA Commercial Rules in DuPage County, Illinois.

12.3 Entire Agreement. This document constitutes the entire agreement and supersedes all prior agreements between the parties regarding the subject matter herein.

12.4 Amendments. Amendments require written consent from both parties.

12.5 Assignment. Neither party may assign this Agreement without the other's written consent, except that TDI may assign in connection with a merger, acquisition, or sale of substantially all assets, provided the assignee assumes all obligations under this Agreement.

12.6 Severability. If any provision of this Agreement is found to be unenforceable, the remainder of the Agreement stays in full force and effect.

12.7 Notices. Written notices shall be delivered to the email addresses on file for each party.`,
  },
];

export default function FullAgreementPage() {
  return (
    <>
      <style jsx global>{`
        @media print {
          .no-print { display: none !important; }
          body { font-size: 11pt; color: black; background: white; }
          .print-section { page-break-inside: avoid; }
        }
      `}</style>

      <div style={{ minHeight: '100vh', background: '#f5f5f5', fontFamily: "'DM Sans', sans-serif" }}>
        {/* Header */}
        <header className="no-print" style={{ background: 'white', borderBottom: '1px solid #E5E7EB', position: 'sticky', top: 0, zIndex: 50 }}>
          <div style={{ maxWidth: 880, margin: '0 auto', padding: '14px 24px' }}>
            <Link href="/creator-portal/agreement" style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#6B7280', fontSize: 14, textDecoration: 'none' }}>
              <ArrowLeft style={{ width: 16, height: 16 }} /> Back to agreement
            </Link>
          </div>
        </header>

        <main style={{ maxWidth: 880, margin: '0 auto', padding: '48px 24px 80px' }}>
          {/* Title */}
          <div style={{ marginBottom: 40, borderBottom: '1px solid #D1D5DB', paddingBottom: 32 }}>
            <h1 style={{ fontSize: 28, fontWeight: 500, color: '#1e2749', margin: '0 0 8px 0', fontFamily: "'Source Serif 4', Georgia, serif" }}>
              Independent Content Creator Agreement
            </h1>
            <p style={{ fontSize: 14, color: '#6B7280', margin: '0 0 4px 0' }}>
              Template version: 2.3 &mdash; May 2026
            </p>
            <p style={{ fontSize: 14, color: '#9CA3AF', margin: 0 }}>
              This agreement becomes effective when signed by both parties.
            </p>
          </div>

          {/* Agreement sections */}
          {SECTIONS.map((section) => (
            <div key={section.number} className="print-section" style={{ marginBottom: 36 }}>
              <h2 style={{
                fontSize: 16, fontWeight: 500, color: '#1e2749',
                textTransform: 'uppercase', letterSpacing: 0.5,
                margin: '0 0 12px 0',
                fontFamily: "'DM Sans', sans-serif",
              }}>
                {section.number}. {section.title}
              </h2>
              <div style={{
                fontSize: 15, color: '#374151', lineHeight: 1.8,
                fontFamily: "'Source Serif 4', Georgia, serif",
                whiteSpace: 'pre-line',
              }}>
                {section.content}
              </div>
            </div>
          ))}

          {/* Footer */}
          <div style={{ borderTop: '1px solid #D1D5DB', paddingTop: 32, marginTop: 48 }}>
            <p style={{ fontSize: 13, color: '#9CA3AF', lineHeight: 1.6 }}>
              Template version: 2.3 &mdash; May 2026. Updates: v2.3 removes content revenue share entirely &mdash; sole compensation is 50% affiliate revenue per board direction.
            </p>
            <p style={{ fontSize: 13, color: '#9CA3AF', marginTop: 8 }}>
              For questions: <a href="mailto:creatorstudio@teachersdeserveit.com" style={{ color: '#2563EB' }}>creatorstudio@teachersdeserveit.com</a>
            </p>
          </div>

          {/* Action buttons */}
          <div className="no-print" style={{ display: 'flex', gap: 12, marginTop: 32 }}>
            <button
              onClick={() => window.print()}
              style={{
                display: 'flex', alignItems: 'center', gap: 8,
                padding: '10px 20px', border: '1px solid #D1D5DB', borderRadius: 10,
                background: 'white', color: '#1e2749', fontSize: 14, fontWeight: 500, cursor: 'pointer',
              }}
            >
              <Printer style={{ width: 16, height: 16 }} />
              Print / save as PDF
            </button>
            <Link
              href="/creator-portal/agreement"
              style={{
                display: 'flex', alignItems: 'center', gap: 8,
                padding: '10px 20px', border: '1px solid #D1D5DB', borderRadius: 10,
                background: 'white', color: '#1e2749', fontSize: 14, fontWeight: 500, textDecoration: 'none',
              }}
            >
              <ArrowLeft style={{ width: 16, height: 16 }} />
              Back to agreement
            </Link>
          </div>
        </main>
      </div>
    </>
  );
}
